// Code generated by stanc v2.34.0
#include <stan/model/model_header.hpp>
namespace code_2_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 21> locations_array__ =
  {" (found before start of program)",
  " (in '/GA/Data-Analytics/Project/PimaDiabetesPrediction/LogisticRegresion/Stan/code_2.stan', line 8, column 2 to column 13)",
  " (in '/GA/Data-Analytics/Project/PimaDiabetesPrediction/LogisticRegresion/Stan/code_2.stan', line 9, column 2 to column 20)",
  " (in '/GA/Data-Analytics/Project/PimaDiabetesPrediction/LogisticRegresion/Stan/code_2.stan', line 10, column 2 to column 16)",
  " (in '/GA/Data-Analytics/Project/PimaDiabetesPrediction/LogisticRegresion/Stan/code_2.stan', line 11, column 2 to column 16)",
  " (in '/GA/Data-Analytics/Project/PimaDiabetesPrediction/LogisticRegresion/Stan/code_2.stan', line 12, column 2 to column 15)",
  " (in '/GA/Data-Analytics/Project/PimaDiabetesPrediction/LogisticRegresion/Stan/code_2.stan', line 13, column 2 to column 20)",
  " (in '/GA/Data-Analytics/Project/PimaDiabetesPrediction/LogisticRegresion/Stan/code_2.stan', line 14, column 2 to column 25)",
  " (in '/GA/Data-Analytics/Project/PimaDiabetesPrediction/LogisticRegresion/Stan/code_2.stan', line 19, column 2 to column 28)",
  " (in '/GA/Data-Analytics/Project/PimaDiabetesPrediction/LogisticRegresion/Stan/code_2.stan', line 20, column 2 to column 33)",
  " (in '/GA/Data-Analytics/Project/PimaDiabetesPrediction/LogisticRegresion/Stan/code_2.stan', line 21, column 2 to column 30)",
  " (in '/GA/Data-Analytics/Project/PimaDiabetesPrediction/LogisticRegresion/Stan/code_2.stan', line 22, column 2 to column 27)",
  " (in '/GA/Data-Analytics/Project/PimaDiabetesPrediction/LogisticRegresion/Stan/code_2.stan', line 23, column 2 to column 27)",
  " (in '/GA/Data-Analytics/Project/PimaDiabetesPrediction/LogisticRegresion/Stan/code_2.stan', line 24, column 2 to column 33)",
  " (in '/GA/Data-Analytics/Project/PimaDiabetesPrediction/LogisticRegresion/Stan/code_2.stan', line 25, column 2 to column 32)",
  " (in '/GA/Data-Analytics/Project/PimaDiabetesPrediction/LogisticRegresion/Stan/code_2.stan', line 28, column 2 to column 150)",
  " (in '/GA/Data-Analytics/Project/PimaDiabetesPrediction/LogisticRegresion/Stan/code_2.stan', line 2, column 2 to column 17)",
  " (in '/GA/Data-Analytics/Project/PimaDiabetesPrediction/LogisticRegresion/Stan/code_2.stan', line 3, column 8 to column 9)",
  " (in '/GA/Data-Analytics/Project/PimaDiabetesPrediction/LogisticRegresion/Stan/code_2.stan', line 3, column 2 to column 35)",
  " (in '/GA/Data-Analytics/Project/PimaDiabetesPrediction/LogisticRegresion/Stan/code_2.stan', line 4, column 9 to column 10)",
  " (in '/GA/Data-Analytics/Project/PimaDiabetesPrediction/LogisticRegresion/Stan/code_2.stan', line 4, column 2 to column 17)"};
class code_2_model final : public model_base_crtp<code_2_model> {
 private:
  int N;
  std::vector<int> y;
  Eigen::Matrix<double,-1,-1> X_data__;
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X{nullptr, 0, 0};
 public:
  ~code_2_model() {}
  code_2_model(stan::io::var_context& context__, unsigned int
               random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "code_2_model_namespace::code_2_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 16;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 16;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 16;
      stan::math::check_greater_or_equal(function__, "N", N, 0);
      current_statement__ = 17;
      stan::math::validate_non_negative_index("y", "N", N);
      current_statement__ = 18;
      context__.validate_dims("data initialization", "y", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      y = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 18;
      y = context__.vals_i("y");
      current_statement__ = 18;
      stan::math::check_greater_or_equal(function__, "y", y, 0);
      current_statement__ = 18;
      stan::math::check_less_or_equal(function__, "y", y, 1);
      current_statement__ = 19;
      stan::math::validate_non_negative_index("X", "N", N);
      current_statement__ = 20;
      context__.validate_dims("data initialization", "X", "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(6)});
      X_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, 6,
                   std::numeric_limits<double>::quiet_NaN());
      new (&X) Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_data__.data(), N, 6);
      {
        std::vector<local_scalar_t__> X_flat__;
        current_statement__ = 20;
        X_flat__ = context__.vals_r("X");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= 6; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            stan::model::assign(X, X_flat__[(pos__ - 1)],
              "assigning variable X", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + 1 + 1 + 1 + 1 + 1;
  }
  inline std::string model_name() const final {
    return "code_2_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.34.0",
             "stancflags = "};
  }
  // Base log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_not_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "code_2_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 1;
      alpha = in__.template read<local_scalar_t__>();
      local_scalar_t__ beta_glucose = DUMMY_VAR__;
      current_statement__ = 2;
      beta_glucose = in__.template read<local_scalar_t__>();
      local_scalar_t__ beta_age = DUMMY_VAR__;
      current_statement__ = 3;
      beta_age = in__.template read<local_scalar_t__>();
      local_scalar_t__ beta_bmi = DUMMY_VAR__;
      current_statement__ = 4;
      beta_bmi = in__.template read<local_scalar_t__>();
      local_scalar_t__ beta_bp = DUMMY_VAR__;
      current_statement__ = 5;
      beta_bp = in__.template read<local_scalar_t__>();
      local_scalar_t__ beta_insulin = DUMMY_VAR__;
      current_statement__ = 6;
      beta_insulin = in__.template read<local_scalar_t__>();
      local_scalar_t__ beta_dpf = DUMMY_VAR__;
      current_statement__ = 7;
      beta_dpf = in__.template read_constrain_lb<local_scalar_t__,
                   jacobian__>(0, lp__);
      {
        current_statement__ = 8;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(alpha, -(0.3), 1.3));
        current_statement__ = 9;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(beta_glucose, 110,
                         25));
        current_statement__ = 10;
        lp_accum__.add(stan::math::exponential_lpdf<propto__>(beta_age, 0.1));
        current_statement__ = 11;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(beta_bmi, 33, 6));
        current_statement__ = 12;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(beta_bp, 75, 12));
        current_statement__ = 13;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(beta_insulin, 130,
                         70));
        current_statement__ = 14;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(beta_dpf, 0.35, 0.35));
        current_statement__ = 15;
        lp_accum__.add(stan::math::bernoulli_logit_lpmf<propto__>(y,
                         stan::math::add(
                           stan::math::add(
                             stan::math::add(
                               stan::math::add(
                                 stan::math::add(
                                   stan::math::add(alpha,
                                     stan::math::multiply(
                                       stan::model::rvalue(X, "X",
                                         stan::model::index_omni(),
                                         stan::model::index_uni(1)),
                                       beta_glucose)),
                                   stan::math::multiply(
                                     stan::model::rvalue(X, "X",
                                       stan::model::index_omni(),
                                       stan::model::index_uni(2)), beta_age)),
                                 stan::math::multiply(
                                   stan::model::rvalue(X, "X",
                                     stan::model::index_omni(),
                                     stan::model::index_uni(3)), beta_bmi)),
                               stan::math::multiply(
                                 stan::model::rvalue(X, "X",
                                   stan::model::index_omni(),
                                   stan::model::index_uni(4)), beta_bp)),
                             stan::math::multiply(
                               stan::model::rvalue(X, "X",
                                 stan::model::index_omni(),
                                 stan::model::index_uni(5)), beta_insulin)),
                           stan::math::multiply(
                             stan::model::rvalue(X, "X",
                               stan::model::index_omni(),
                               stan::model::index_uni(6)), beta_dpf))));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  // Reverse mode autodiff log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "code_2_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 1;
      alpha = in__.template read<local_scalar_t__>();
      local_scalar_t__ beta_glucose = DUMMY_VAR__;
      current_statement__ = 2;
      beta_glucose = in__.template read<local_scalar_t__>();
      local_scalar_t__ beta_age = DUMMY_VAR__;
      current_statement__ = 3;
      beta_age = in__.template read<local_scalar_t__>();
      local_scalar_t__ beta_bmi = DUMMY_VAR__;
      current_statement__ = 4;
      beta_bmi = in__.template read<local_scalar_t__>();
      local_scalar_t__ beta_bp = DUMMY_VAR__;
      current_statement__ = 5;
      beta_bp = in__.template read<local_scalar_t__>();
      local_scalar_t__ beta_insulin = DUMMY_VAR__;
      current_statement__ = 6;
      beta_insulin = in__.template read<local_scalar_t__>();
      local_scalar_t__ beta_dpf = DUMMY_VAR__;
      current_statement__ = 7;
      beta_dpf = in__.template read_constrain_lb<local_scalar_t__,
                   jacobian__>(0, lp__);
      {
        current_statement__ = 8;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(alpha, -(0.3), 1.3));
        current_statement__ = 9;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(beta_glucose, 110,
                         25));
        current_statement__ = 10;
        lp_accum__.add(stan::math::exponential_lpdf<propto__>(beta_age, 0.1));
        current_statement__ = 11;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(beta_bmi, 33, 6));
        current_statement__ = 12;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(beta_bp, 75, 12));
        current_statement__ = 13;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(beta_insulin, 130,
                         70));
        current_statement__ = 14;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(beta_dpf, 0.35, 0.35));
        current_statement__ = 15;
        lp_accum__.add(stan::math::bernoulli_logit_lpmf<propto__>(y,
                         stan::math::add(
                           stan::math::add(
                             stan::math::add(
                               stan::math::add(
                                 stan::math::add(
                                   stan::math::add(alpha,
                                     stan::math::multiply(
                                       stan::model::rvalue(X, "X",
                                         stan::model::index_omni(),
                                         stan::model::index_uni(1)),
                                       beta_glucose)),
                                   stan::math::multiply(
                                     stan::model::rvalue(X, "X",
                                       stan::model::index_omni(),
                                       stan::model::index_uni(2)), beta_age)),
                                 stan::math::multiply(
                                   stan::model::rvalue(X, "X",
                                     stan::model::index_omni(),
                                     stan::model::index_uni(3)), beta_bmi)),
                               stan::math::multiply(
                                 stan::model::rvalue(X, "X",
                                   stan::model::index_omni(),
                                   stan::model::index_uni(4)), beta_bp)),
                             stan::math::multiply(
                               stan::model::rvalue(X, "X",
                                 stan::model::index_omni(),
                                 stan::model::index_uni(5)), beta_insulin)),
                           stan::math::multiply(
                             stan::model::rvalue(X, "X",
                               stan::model::index_omni(),
                               stan::model::index_uni(6)), beta_dpf))));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    // suppress unused var warning
    (void) jacobian__;
    static constexpr const char* function__ =
      "code_2_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double alpha = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      alpha = in__.template read<local_scalar_t__>();
      double beta_glucose = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      beta_glucose = in__.template read<local_scalar_t__>();
      double beta_age = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      beta_age = in__.template read<local_scalar_t__>();
      double beta_bmi = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      beta_bmi = in__.template read<local_scalar_t__>();
      double beta_bp = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      beta_bp = in__.template read<local_scalar_t__>();
      double beta_insulin = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 6;
      beta_insulin = in__.template read<local_scalar_t__>();
      double beta_dpf = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 7;
      beta_dpf = in__.template read_constrain_lb<local_scalar_t__,
                   jacobian__>(0, lp__);
      out__.write(alpha);
      out__.write(beta_glucose);
      out__.write(beta_age);
      out__.write(beta_bmi);
      out__.write(beta_bp);
      out__.write(beta_insulin);
      out__.write(beta_dpf);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 1;
      alpha = in__.read<local_scalar_t__>();
      out__.write(alpha);
      local_scalar_t__ beta_glucose = DUMMY_VAR__;
      current_statement__ = 2;
      beta_glucose = in__.read<local_scalar_t__>();
      out__.write(beta_glucose);
      local_scalar_t__ beta_age = DUMMY_VAR__;
      current_statement__ = 3;
      beta_age = in__.read<local_scalar_t__>();
      out__.write(beta_age);
      local_scalar_t__ beta_bmi = DUMMY_VAR__;
      current_statement__ = 4;
      beta_bmi = in__.read<local_scalar_t__>();
      out__.write(beta_bmi);
      local_scalar_t__ beta_bp = DUMMY_VAR__;
      current_statement__ = 5;
      beta_bp = in__.read<local_scalar_t__>();
      out__.write(beta_bp);
      local_scalar_t__ beta_insulin = DUMMY_VAR__;
      current_statement__ = 6;
      beta_insulin = in__.read<local_scalar_t__>();
      out__.write(beta_insulin);
      local_scalar_t__ beta_dpf = DUMMY_VAR__;
      current_statement__ = 7;
      beta_dpf = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, beta_dpf);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "alpha", "double",
        std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "beta_glucose",
        "double", std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "beta_age",
        "double", std::vector<size_t>{});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "beta_bmi",
        "double", std::vector<size_t>{});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "beta_bp",
        "double", std::vector<size_t>{});
      current_statement__ = 6;
      context__.validate_dims("parameter initialization", "beta_insulin",
        "double", std::vector<size_t>{});
      current_statement__ = 7;
      context__.validate_dims("parameter initialization", "beta_dpf",
        "double", std::vector<size_t>{});
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 1;
      alpha = context__.vals_r("alpha")[(1 - 1)];
      out__.write(alpha);
      local_scalar_t__ beta_glucose = DUMMY_VAR__;
      current_statement__ = 2;
      beta_glucose = context__.vals_r("beta_glucose")[(1 - 1)];
      out__.write(beta_glucose);
      local_scalar_t__ beta_age = DUMMY_VAR__;
      current_statement__ = 3;
      beta_age = context__.vals_r("beta_age")[(1 - 1)];
      out__.write(beta_age);
      local_scalar_t__ beta_bmi = DUMMY_VAR__;
      current_statement__ = 4;
      beta_bmi = context__.vals_r("beta_bmi")[(1 - 1)];
      out__.write(beta_bmi);
      local_scalar_t__ beta_bp = DUMMY_VAR__;
      current_statement__ = 5;
      beta_bp = context__.vals_r("beta_bp")[(1 - 1)];
      out__.write(beta_bp);
      local_scalar_t__ beta_insulin = DUMMY_VAR__;
      current_statement__ = 6;
      beta_insulin = context__.vals_r("beta_insulin")[(1 - 1)];
      out__.write(beta_insulin);
      local_scalar_t__ beta_dpf = DUMMY_VAR__;
      current_statement__ = 7;
      beta_dpf = context__.vals_r("beta_dpf")[(1 - 1)];
      out__.write_free_lb(0, beta_dpf);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"alpha", "beta_glucose", "beta_age",
                "beta_bmi", "beta_bp", "beta_insulin", "beta_dpf"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "alpha");
    param_names__.emplace_back(std::string() + "beta_glucose");
    param_names__.emplace_back(std::string() + "beta_age");
    param_names__.emplace_back(std::string() + "beta_bmi");
    param_names__.emplace_back(std::string() + "beta_bp");
    param_names__.emplace_back(std::string() + "beta_insulin");
    param_names__.emplace_back(std::string() + "beta_dpf");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "alpha");
    param_names__.emplace_back(std::string() + "beta_glucose");
    param_names__.emplace_back(std::string() + "beta_age");
    param_names__.emplace_back(std::string() + "beta_bmi");
    param_names__.emplace_back(std::string() + "beta_bp");
    param_names__.emplace_back(std::string() + "beta_insulin");
    param_names__.emplace_back(std::string() + "beta_dpf");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_glucose\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_age\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_bmi\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_bp\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_insulin\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_dpf\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_glucose\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_age\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_bmi\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_bp\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_insulin\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_dpf\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((((1 + 1) + 1) + 1) + 1) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((((1 + 1) + 1) + 1) + 1) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = code_2_model_namespace::code_2_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return code_2_model_namespace::profiles__;
}
#endif